#ifndef SPEL_H
#define SPEL_H

#define DEFAULT_WIDTH 800
#define DEFAULT_HEIGHT 600

#define PLAYER_WIDTH 90
#define PLAYER_HEIGHT 100
#define PLAYER_SPEED 6
#define JUMP_FORCE 15
#define GRAVITY 1

#define CAMERA_SMOOTHING 0.05f
#define CAMERA_DEADZONE 150

#define WALK_FRAME_COUNT 2
#define ANIMATION_SPEED 10


#endif // SPEL_H
